connectedin/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
#from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('perfis.urls')),
    #url(r'^$', include('perfis.urls')),
    re_path(r'^', include('perfis.urls')),
    re_path(r'^', include('usuarios.urls')),
]

perfis/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
#from django.conf.utls import patterns, url
#
from perfis.views import index, exibir, convidar, aceitar

urlpatterns = [
    # url(r'^', views.index)
    #path('', index),
    #path('perfis/', exibir),
    re_path(r'^$', index, name="index"),
    re_path(r'^perfis/(?P<perfil_id>\d+)$', exibir, name="exibir"),
    re_path(r'^perfis/(?P<perfil_id>\d+)/convidar$', convidar, name="convidar"),
    re_path(r'^convite/(?P<convite_id>\d+)/aceitar', aceitar, name="aceitar"),

    #re_path(r'^perfis/(?P<perfil_id>\d+)$', exibir, name="exibir"),

]

usuarios/urls.py
#from django.conf.utls import patterns, url
from django.contrib import admin
from django.urls import include, path, re_path
#from django.conf.urls import url
from usuarios.views import RegistrarUsuarioView
from django.contrib.auth.views import login, logout_then_login
#from django.contrib.auth import views as auth_views

urlpatterns = [
    # url(r'^', views.index)
    #path('', index),
    #path('perfis/', exibir),
    re_path(r'^registrar/$', RegistrarUsuarioView.as_view(), name="registrar"),
    re_path(r'^login/$', login, { 'template_name' : 'login.html'}, name="login"),
    re_path(r'^logout/$', logout_then_login, { 'login_url' : '/login/'}, name="logout"),
    #re_path(r'^perfis/(?P<perfil_id>\d+)$', exibir, name="exibir"),
    #re_path(r'^perfis/(?P<perfil_id>\d+)/convidar$', convidar, name='convidar'),
    #re_path(r'^convite/(?P<convite_id>\d+)/aceitar$', aceitar, name='aceitar'),
]

perfis/models.py
from django.db import models
from django.contrib.auth.models import User
class Perfil(models.Model):
  nome = models.CharField(max_length=255, null=False)
  #email = models.CharField(max_length=255, null=False)
  telefone = models.CharField(max_length=15, null=False)
  nome_empresa = models.CharField(max_length=255, null=False)
  contatos = models.ManyToManyField('self')
  usuario = models.OneToOneField(User, related_name="perfil", on_delete=models.CASCADE)

  @property
  def email(self):
    return self.usuario.email

  def convidar(self, perfil_convidado):
    Convite(solicitante=self, convidado=perfil_convidado).save()

  def __str__(self):
    return str(self.__dict__)

  def __cmp__(self, other):
    return self.__dict__ == other.__dict__

class Convite(models.Model):
  solicitante = models.ForeignKey(Perfil, related_name='convites_feitos', on_delete=models.CASCADE)
  convidado = models.ForeignKey(Perfil, related_name='convites_recebidos', on_delete=models.CASCADE)

  def aceitar(self):
    self.convidado.contatos.add(self.solicitante)
    self.solicitante.contatos.add(self.convidado)
    self.delete()

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
  nome = forms.CharField(required=True)
  email = forms.EmailField(required=True)
  senha = forms.CharField(required=True)
  telefone = forms.CharField(required=False)
  nome_empresa = forms.CharField(required=False)

  def is_valid(self):
    valid = True
    if not super(RegistrarUsuarioForm, self).is_valid():
      self.adiciona_erro("Por favor, verifique os dados informados")
      valid = False

    user_exists = User.objects.filter(username=self.data['nome']).exists()

    if user_exists:
      self.adiciona_erro("Usuário já existente")
      valid = False
    return valid

  def adiciona_erro(self, mensagem):
    errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
    errors.append(mensagem)

perfis/views.py
from django.shortcuts import render
from django.http import HttpResponse
from perfis.models import Perfil, Convite
from django.shortcuts import redirect

from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.http import require_http_methods

from django.contrib.auth.models import User

from django.http import HttpResponseForbidden

import logging
logger = logging.getLogger(__name__)


@login_required
@require_http_methods(["GET"])
def index(request):


    perfis = None
    perfil_logado = None

    try:
       perfis = Perfil.objects.all()
    except Exception as error:
        print("Nenhum usuário para mostrar na tela de index")

    try:
       perfil_logado = get_perfil_logado(request)
    except Exception as error:
        print("Nenhum usuário logado %s" %(error))



    return render(request, 'index.html', { 'perfis' : perfis,
   'perfil_logado' : perfil_logado})

@login_required
def exibir(request, perfil_id):

    perfil = None
    perfil_logado = None
    try:
        perfil = Perfil.objects.get(id=perfil_id)
        perfil_logado = get_perfil_logado(request)
    except Exception as error:
        print("Consulta do usuario com o id %s não encontrado" %(perfil_id))

    if perfil == perfil_logado:
        return render(request, 'perfil.html', {'perfil' : perfil, 'perfil_logado' : perfil_logado,
           'perfil_igual_perfil_logado' : True})

    ja_eh_contato = perfil in perfil_logado.contatos.all()

    return render(request, 'perfil.html', {'perfil' : perfil, 'perfil_logado' : perfil_logado,
                   'ja_eh_contato' : ja_eh_contato})

@login_required
@permission_required('perfis.add_convite', raise_exception=False)
def convidar(request, perfil_id):

    if not request.user.has_perm('perfis.add_convite'):
        return HttpResponseForbidden('Acesso negado')

    perfil_a_convidar = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    perfil_logado.convidar(perfil_a_convidar)
    return redirect('index');

@login_required
def get_perfil_logado(request):
    if request.user.is_authenticated:
        pass

    return request.user.perfil

@login_required
def aceitar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.aceitar()
    return redirect('index')

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.views.generic.base import View
from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm

class RegistrarUsuarioView(View):
  template_name = "registrar.html"

  def get(self, request):
    return render(request, self.template_name)

  def post(self, request):
    form = RegistrarUsuarioForm(request.POST)
    if form.is_valid():
      dados_form = form.data
      usuario = User.objects.create_user(dados_form['nome'], dados_form['email'], dados_form['senha'])
      perfil = Perfil(
                nome=dados_form['nome'],
                telefone=dados_form['telefone'],
                nome_empresa=dados_form['nome_empresa'],
                usuario=usuario)

      perfil.save()
      return redirect('index')

    return render(request, self.template_name, { 'form': form })

perfis/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
	<link href="{% static "styles/main.css" %}" rel="stylesheet">
	<title>ConnectedIn</title>
</head>
<body>
	<div class="container">
		<div class="header">
			<ul class="nav nav-pills pull-right">
				<li class=""><a href="{% url 'index' %}">{{perfil_logado.nome}}</a></li>
				<li class=""><a href="{% url 'logout' %}">Logout</a></li>
			</ul>
			<h3 class="text-muted">ConnectedIn</h3>
		</div>
		<div class="row content">
			{% block body %}
			{% endblock %}
		</div>
	</div>
</body>
</html>

perfis/templates/base_convidar.html
{% if ja_eh_contato %}
  <div class="well well-sm">Vocês estão conectados!</div>
{% else %}
  <a href="{% url 'convidar' perfil.id %}" class="btn btn-success" role="button">convidar</a>
{% endif %}

perfis/templates/index.html
{% extends "base.html" %}
{% block body %}
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong>Todos os Perfis</strong>
    </div>
    {% if perfis %}
    <ul>
      {% for perfil in perfis %}
      <li>
        <a href="{% url 'exibir' perfil.id %}">{{ perfil.nome }}</a> / {{ perfil.email }}
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <div class="panel-body">
      <p>Nenhum Perfil encontrado</p>
    </div>
    {% endif %}
  </div>
  <div class="panel panel-default">
    {% with total_de_convites=perfil_logado.convites_recebidos.count %}
    {% if total_de_convites %}
    <div class="panel-heading">
      <strong>
        Você tem {{ total_de_convites }}
        convite{{ total_de_convites|pluralize }} aguardando aprovação
      </strong>
    </div>
    <ul class="list-group">
      {% for convite in perfil_logado.convites_recebidos.all %}
      <li class="list-group-item">
        {{ convite.solicitante.nome }}
        <a href="{% url 'aceitar' convite.id %}" class="pull-right">aceitar</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <div class="panel-body">
      <p>Nenhum convite recebido :(</p>
    </div>
    {% endif %}
    {% endwith %}
  </div>
  <div class="panel panel-default">
    {% with total_de_contatos=perfil_logado.contatos.count %}
    {% if total_de_contatos %}
    <div class="panel-heading">
      <strong>Você tem {{total_de_contatos}} contato{{ total_de_contatos|pluralize }}</strong>
    </div>
    <ul class="list-group">
      {% for contato in perfil_logado.contatos.all %}
      <a href="{% url 'exibir' contato.id %}" class="list-group-item">{{ contato.nome }} // {{ contato.email }}</a>
      {% endfor %}
    </ul>
    {% else %}
    <div class="panel-body">
      <p>Você não possui contatos no momento :(</p>
    </div>
    {% endif %}
    {% endwith %}
  </div>
</div>
{% endblock %}

perfis/templates/perfil.html
{% extends "base.html" %}
{% block body %}
<div class="row">
  <div class="col-lg-12">
    {% if not perfil %}
    <div class="well well-sm">Perfil não Encontrado</div>
    {% else %}
    <h2 style="margin-top:0">{{perfil.nome}}</h2>
    <address>
      <strong>{{perfil.nome_empresa}}</strong><br>
      <abbr title="Telefone">Tel:</abbr> {{perfil.telefone}}<br>
      <a href="mailto:{{perfil.email}}">{{perfil.email}}</a>
    </address>
    {% if not perfil_igual_perfil_logado %}
    {% include "base_convidar.html" %}
    {% endif %}
  </div>
  {% endif %}
</div>
{% endblock %}

usuarios/templates/base_usuario.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "styles/main.css" %}" rel="stylesheet">
    <title>ConnectedIn</title>
  </head>
  <body>
    <div class="container">
      {% block body %}
      {% endblock %}
    </div>
  </body>
</html>

usuarios/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}

    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        <hr />
        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Por favor, verifique o Email e/ou Senha informados
          </div>
        {% endif %}

        <a href="{% url 'registrar' %}">registre-se</a>
    </form>

{% endblock %}

usuarios/templates/registrar.html
{% extends "base_usuario.html" %}
{% block body %}
<form class="form-signin" role="form" action="{% url 'registrar' %}" method="POST">
  {% csrf_token%}
  <h2 class="form-signin-heading"> Crie seu Usuário </h2>
  <input type="text" id="id_email" value="{{ form.email.value }}" name="email" class="form-control" placeholder="Email *" required autofocus>
  <input type="text" id="id_nome" value="{{ form.nome.value }}" name="nome" class="form-control" placeholder="Nome *" required>
  <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *" required>

  <hr />

  <input type="text" id="id_telefone" value="{{ form.telefone.value }}" name="telefone" class="form-control" placeholder="Telefone">
  <input type="text" id="id_nome_empresa" value="{{ form.nome_empresa.value }}" name="nome_empresa" class="form-control" placeholder="Nome da Empresa">

  <hr />

  <button class="btn primary btn-lg btn-primary btn-block" type="submit" value="login">Registrar</button>

  <hr />

  {% if form.errors %}
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true" >&times;</button>
      {{ form.non_field_errors }}
      {% for field in form %}
        <div class="panel-body">
          {% if field.errors %}
            <p><span>{{ field.label_tag }}</span>{{ field.errors }}</p>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  {% endif %}
  Já é usuario? <a href="{% url 'login' %}">Faça login</a>
</form>
{% endblock %}